apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-lifecycle-config
data:
  ilm-policy.json: |
    {
      "policy": {
        "phases": {
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "{{ .Values.es.rolloverAge }}"
              }
            }
          },
          "delete": {
            "min_age": "{{ .Values.es.deleteAge }}",
            "actions": {
              "delete": {}
            }
          }
        }
      }
    }
